#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define TAILLE_BAR 90
#define LARGEUR_FENETRE 1024
#define HAUTEUR_FENETRE 768
#define HAUTEUR_BAR_IMAGE 10
#define TAILLE_IMAGE 80

#endif // CONST_H_INCLUDED
