#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define TAILLE_BAR 90
#define LARGEUR_FENETRE 1024
#define HAUTEUR_FENETRE 768
#define HAUTEUR_BAR_IMAGE 10
#define TAILLE_IMAGE 80

int const COLOR[8] = {ROUGE, BLEU, VERTFLUO, JAUNESOMBRE, CYAN, MARRON, VIOLET, ORANGE};

#endif // CONST_H_INCLUDED
